# Generated by Django 2.0.6 on 2018-06-26 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objetos_aprendizaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto_aprendizaje',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Profesor'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='objetos_aprendizaje.Comentario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='objeto_aprendizaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos_aprendizaje.Objeto_Aprendizaje'),
        ),
    ]
